Algoritmo "exercicio_crescente"

Var

   x, y: inteiro

Inicio


      escreval("Digite dois números: ")
      leia(x)
      leia(y)
      
      enquanto (x <> y) faca

         se x < y entao
               escreval("Ordem crescente.")
         senao
               escreval("Ordem decrescente.")
         fimse

         escreval("Digite outros dois números: ")
         leia(x)
         leia(y)
      fimenquanto








Fimalgoritmo